services:
  - type: web
    name: zhijireminderbackend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_TYPE
        value: postgresql
      - key: RENDER
        value: true
      - key: POSTGRES_INTERNAL_URL
        value: postgresql://zhi_ji_xia_user:biPoDHMdRoOoqQUrLFD7zIiZKolhxop7@dpg-d76cfmhaae7s73c21lig-a/zhi_ji_xia
      - key: POSTGRES_EXTERNAL_URL
        value: postgresql://zhi_ji_xia_user:biPoDHMdRoOoqQUrLFD7zIiZKolhxop7@dpg-d76cfmhaae7s73c21lig-a.singapore-postgres.render.com/zhi_ji_xia
      - key: REMINDER_CHECK_INTERVAL_MINUTES
        value: 1
    healthCheckPath: /
    autoDeploy: true
